### ISSUE TITLE
How do you keep your stuff uptodate?

### ISSUE THREAD

**Issue by tuxpeople** [sseneca/sserver#1]
Hi

Greetings from over the channel :-)

Very interesting what you are doing here. And welcome to Flux v2, I startet with it and have skipped v1.

I do have a question: You hardcoded versions of Docker images, chart versions etc. This is best practice, I know. But how can one know about new versions? How do you keep track of new versions?

Br
Thomas

**Comment by sseneca** [comment]
Hi :wave:

Flux has a feature that automatically updates images depending on a defined policy, like semver or regex. You can see an example of how this was done with Fluxv1 here: https://github.com/sseneca/k8s-server/blob/master/nextcloud/release.yaml#L9 Fluxv2 [changes how this works quite a lot](
https://fluxcd.io/docs/guides/image-update/ ) and I haven't migrated that part yet; hopefully I will soon.

I also use RSS/Atom feeds a lot. For example, GitHub offers Atom feeds for releases, e.g. for Nextcloud you can use this Atom feed: https://github.com/nextcloud/server/releases.atom. This way I can also track updates for almost anything I host.

Hope this helps!

**Comment by tuxpeople** [comment]
Helps a lot, thanks!

I was now able to get [Renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate/) working. It does make Pull Requests for image and helm-chart updates. I try to use helm charts a lot.
